name: Terraform Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform-fmt:
    name: Check Terraform Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Run terraform fmt
        run: terraform fmt -check -recursive
